FROM debian:stable-slim

RUN apt update -y
RUN apt install -y build-essential
RUN apt install -y opam
RUN apt install -y git bash curl
# for TSAN
RUN apt install -y libunwind-dev pkgconf libtsan2

WORKDIR /home/github
RUN opam init --auto-setup --disable-sandboxing --bare -y
RUN opam switch create ./ ocaml-variants.5.3.0+options ocaml-option-tsan

RUN opam install -y dune
RUN opam install -y core.v0.17.1 async.v0.17.0 sexp.v0.17.0 nice_parser.1.0.0 menhir.20250912 ocamlformat.0.28.1 bisect_ppx.2.8.3

