FROM debian:stable-slim AS fetcher

RUN apt update -y
RUN apt install -y git bash curl

# needed for Chromium tools
RUN apt install -y lsb-release
RUN apt install -y python3
RUN apt install -y sudo file

WORKDIR /workdir
RUN git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
ENV PATH="/workdir/depot_tools:/go/bin:$PATH"

WORKDIR /workdir/chromium
RUN gclient metrics --opt-out
RUN fetch --nohooks --no-history chromium

FROM debian:stable-slim

RUN apt update -y
RUN apt install -y git bash curl
RUN apt install -y golang

# needed for Chromium tools
RUN apt install -y lsb-release
RUN apt install -y python3
RUN apt install -y sudo file

RUN go version
RUN go install github.com/bazelbuild/buildtools/buildifier@latest

ENV PATH="/workdir/depot_tools:/go/bin:$PATH"

WORKDIR /workdir
COPY --from=fetcher /workdir/depot_tools ./depot_tools
COPY --from=fetcher /workdir/chromium/src/build ./build

RUN gclient metrics --opt-out
RUN ./build/install-build-deps.sh
