FROM debian:stable-slim

RUN apt update -y
RUN apt install -y git bash curl

# needed for Chromium tools
RUN apt install -y lsb-release
RUN apt install -y python3
RUN apt install -y sudo file

RUN apt install -y golang
RUN go version
RUN go install github.com/bazelbuild/buildtools/buildifier@latest

WORKDIR /workdir
RUN git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
ENV PATH="/workdir/depot_tools:/root/go/bin:$PATH"
RUN gclient metrics --opt-out

WORKDIR /workdir/build
RUN git clone --no-checkout --depth=1 --filter=tree:0 https://chromium.googlesource.com/chromium/src.git
WORKDIR /workdir/build/src
RUN git sparse-checkout set --no-cone /build
RUN git checkout
RUN ./build/install-build-deps.sh

WORKDIR /workdir
