FROM debian:stable-slim

RUN apt update -y
RUN apt install -y build-essential
RUN apt install -y opam
RUN apt install -y git bash curl
# for TSAN
RUN apt install -y libunwind-dev pkgconf libtsan2

WORKDIR /github/home
RUN opam init --auto-setup --disable-sandboxing --bare -y
RUN opam switch create ./ ocaml-variants.5.3.0+options ocaml-option-tsan

RUN opam install -y dune

RUN cp -a /github/home/. /root

# `opam env` environment hard-coded into the container
ENV OPAM_SWITCH_PREFIX='/github/home/_opam'
ENV OCAMLTOP_INCLUDE_PATH='/github/home/_opam/lib/toplevel'
ENV CAML_LD_LIBRARY_PATH='/github/home/_opam/lib/stublibs:/github/home/_opam/lib/ocaml/stublibs:/github/home/_opam/lib/ocaml'
ENV OCAML_TOPLEVEL_PATH='/github/home/_opam/lib/toplevel'
ENV MANPATH=':/github/home/_opam/man'
ENV PATH='/github/home/_opam/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

